version: "2"
services:
    server:
        build: ./
        command: sh -c 'npm install && npm start'
        ports:
            - 80:3000
        #depends_on:
         #   - mongo
        environment:
            - NODE_ENV=development